inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

model_store=./model_store

# Turn off TS system metrics so it doesn't require nvgpu
disable_system_metrics=true

# Limits for a single-GPU node
default_workers_per_model=1
number_of_netty_threads=32
job_queue_size=1000
max_request_size=6553500
max_response_size=6553500
